/// Flutter icons EnlistAppIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EnlistAppIcon
///      fonts:
///       - asset: fonts/EnlistAppIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EnlistAppIcon {
  EnlistAppIcon._();

  static const _kFontFam = 'EnlistAppIcon';

  static const IconData agua_radiador_aceite = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData aire_acondicionado = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData aseo_interno_externo = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData avantel_celular = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData bateria_niveles_agua = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData bocina = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData botiquin = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData calcomania = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData cinturon_seguridad = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData contrasena = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData direccion_transmision = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData dispositivo_de_velocidad = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData documentos_conductor = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData documentos_vehiculo = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData equipo_carretera = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData escalera_conductor = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData escalera_pasajero = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData espejos_retrovisores = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData extintor = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData freno_emergencia = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData goteo_motor = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData herramientas = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData limpia_parabrisas = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData linterna = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData listo_ok = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData llanta_de_repuesto = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData llantas = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData luces = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData nosotros = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData ocultar_o_ver = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData revision_filtros = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData ruteros = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData salir = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData silla_conductor = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData silleteria = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData sistema_frenos = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData soporte = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData soporte2 = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData tapas_radiador = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData tension_correas = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData tomar_foto = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData usuario = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData historial = const IconData(0xe82a, fontFamily: _kFontFam);
}
