name: GPS_CONTROL
description: Una aplicacion de GPS CONTROL.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_login:
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  intl: ^0.16.0
  http: ^0.12.0+2
  flutter_slidable: "^0.5.4"
  odoo_api: ^1.0.4
  sqflite: ^1.1.7
  path_provider: ^1.4.5
  modal_progress_hud: ^0.1.3
  shared_preferences: ^0.4.2
  # scoped model
  scoped_model: ^1.0.1
  # dependency injection
  get_it: ^1.0.3
  color: any
  flat_icons_flutter: ^1.0.2
  camera:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/icon/favicon.png
  - assets/logo1.png
  - assets/images/ecorp-lightgreen.png

